<?php

namespace Database\Seeders;
use App\Models\Champion;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ChampionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void {
    Champion::create(['name' => 'Aatrox', 'photo' => 'photo/Aatrox.png','square' => 'square/AatroxSquare.png']);
    Champion::create(['name' => 'Ahri', 'photo' => 'photo/Ahri.png','square' => 'square/AhriSquare.png']);
    Champion::create(['name' => 'Akali', 'photo' => 'photo/Akali.png','square' => 'square/AkaliSquare.png']);
    Champion::create(['name' => 'Alistar', 'photo' => 'photo/Alistar.png','square' => 'square/AlistarSquare.png']);
    Champion::create(['name' => 'Amumu', 'photo' => 'photo/Amumu.png','square' => 'square/AmumuSquare.png']);
    Champion::create(['name' => 'Anivia', 'photo' => 'photo/Aanivia.png','square' => 'square/AniviaSquare.png']);
    Champion::create(['name' => 'Annie', 'photo' => 'photo/Annie.png','square' => 'square/AnnieSquare.png']);
    Champion::create(['name' => 'Aphelios', 'photo'  => 'photo/Aphelios.png','square' => 'square/ApheliosSquare.png']);
    Champion::create(['name' => 'Ashe', 'photo' => 'photo/Ashe.png','square' => 'square/AsheSquare.png']);
    Champion::create(['name' => 'Aurelion Sol', 'photo' => 'photo/Aurelion Sol.png','square' => 'square/AurelionSolSquare.png']);
    Champion::create(['name' => 'Azir', 'photo' => 'photo/Azir.png','square' => 'square/AzirSquare.png']);
    Champion::create(['name' => 'Bard', 'photo' => 'photo/Bard.png','square' => 'square/BardSquare.png']);
    Champion::create(['name' => 'Blitzcrank', 'photo' => 'photo/Blitzcrank.png','square' => 'square/BlitzcrankSquare.png']);
    Champion::create(['name' => 'Brand', 'photo' => 'photo/Brand.png','square' => 'square/BrandSquare.png']);
    Champion::create(['name' => 'Braum', 'photo' => 'photo/Braum.png','square' => 'square/BraumSquare.png']);
    Champion::create(['name' => 'Caitlyn', 'photo' => 'photo/Caitlyn.png','square' => 'square/CaitlynSquare.png']);
    Champion::create(['name' => 'Camille', 'photo' => 'photo/Camille.png','square' => 'square/CamilleSquare.png']);
    Champion::create(['name' => 'Cassiopeia', 'photo' => 'photo/Cassiopeia.png','square' => 'square/CassiopeiaSquare.png']);
    Champion::create(['name' => 'Cho\'Gath', 'photo' => 'photo/Cho\'Gath.png','square' => 'square/ChoGathSquare.png']);
    Champion::create(['name' => 'Corki', 'photo' => 'photo/Corki.png','square' => 'square/CorkiSquare.png']);
    Champion::create(['name' => 'Darius', 'photo' => 'photo/Darius.png','square' => 'square/DariusSquare.png']);
    Champion::create(['name' => 'Diana', 'photo' => 'photo/Diana.png','square' => 'square/DianaSquare.png']);
    Champion::create(['name' => 'Dr. Mundo', 'photo' => 'photo/Dr. Mundo.png','square' => 'square/DrMundoSquare.png']);
    Champion::create(['name' => 'Draven', 'photo' => 'photo/Draven.png','square' => 'square/DravenSquare.png']);
    Champion::create(['name' => 'Ekko', 'photo' => 'photo/Ekko.png','square' => 'square/EkkoSquare.png']);
    Champion::create(['name' => 'Elise', 'photo' => 'photo/Elise.png','square' => 'square/EliseSquare.png']);
    Champion::create(['name' => 'Evelynn', 'photo' => 'photo/Evelynn.png','square' => 'square/EvelynnSquare.png']);
    Champion::create(['name' => 'Ezreal', 'photo' => 'photo/Ezreal.png','square' => 'square/EzrealSquare.png']);
    Champion::create(['name' => 'Fiddlesticks', 'photo' => 'photo/Fiddlesticks.png','square' => 'square/FiddlesticksSquare.png']);
    Champion::create(['name' => 'Fiora', 'photo' => 'photo/Fiora.png','square' => 'square/FioraSquare.png']);
    Champion::create(['name' => 'Fizz', 'photo' => 'photo/Fizz.png','square' => 'square/FizzSquare.png']);
    Champion::create(['name' => 'Galio', 'photo' => 'photo/Galio.png','square' => 'square/GalioSquare.png']);
    Champion::create(['name' => 'Gangplank', 'photo' => 'photo/Gangplank.png','square' => 'square/GangplankSquare.png']);
    Champion::create(['name' => 'Garen', 'photo' => 'photo/Garen.png','square' => 'square/GarenSquare.png']);
    Champion::create(['name' => 'Gnar', 'photo' => 'photo/Gnar.png','square' => 'square/GnarSquare.png']);
    Champion::create(['name' => 'Gragas', 'photo' => 'photo/Gragas.png','square' => 'square/GragasSquare.png']);
    Champion::create(['name' => 'Graves', 'photo' => 'photo/Graves.png','square' => 'square/GravesSquare.png']);
    Champion::create(['name' => 'Hecarim', 'photo' => 'photo/Hecarim.png','square' => 'square/HecarimSquare.png']);
    Champion::create(['name' => 'Heimerdinger', 'photo' => 'photo/Heimerdinger.png','square' => 'square/HeimerdingerSquare.png']);
    Champion::create(['name' => 'Illaoi', 'photo' => 'photo/Illaoi.png','square' => 'square/IllaoiSquare.png']);
    Champion::create(['name' => 'Irelia', 'photo' => 'photo/Irelia.png','square' => 'square/IreliaSquare.png']);
    Champion::create(['name' => 'Ivern', 'photo' => 'photo/Ivern.png','square' => 'square/IvernSquare.png']);
    Champion::create(['name' => 'Janna', 'photo' => 'photo/Janna.png','square' => 'square/JannaSquare.png']);
    Champion::create(['name' => 'Jarvan IV', 'photo' => 'photo/Jarvan IV.png','square' => 'square/JarvanIVSquare.png']);
    Champion::create(['name' => 'Jax', 'photo' => 'photo/Jax.png','square' => 'square/JaxSquare.png']);
    Champion::create(['name' => 'Jayce', 'photo' => 'photo/Jayce.png','square' => 'square/JayceSquare.png']);
    Champion::create(['name' => 'Jhin', 'photo' => 'photo/Jhin.png','square' => 'square/JhinSquare.png']);
    Champion::create(['name' => 'Jinx', 'photo' => 'photo/Jinx.png','square' => 'square/JinxSquare.png']);
    Champion::create(['name' => 'Kai\'Sa', 'photo' => 'photo/Kai\'Sa.png','square' => 'square/KaiSaSquare.png']);
    Champion::create(['name' => 'Kalista', 'photo' => 'photo/Kalista.png','square' => 'square/KalistaSquare.png']);
    Champion::create(['name' => 'Karma', 'photo' => 'photo/Karma.png','square' => 'square/KarmaSquare.png']);
    Champion::create(['name' => 'Karthus', 'photo' => 'photo/Karthus.png','square' => 'square/KarthusSquare.png']);
    Champion::create(['name' => 'Kassadin', 'photo' => 'photo/Kassadin.png','square' => 'square/KassadinSquare.png']);
    Champion::create(['name' => 'Katarina', 'photo' => 'photo/Katarina.png','square' => 'square/KatarinaSquare.png']);
    Champion::create(['name' => 'Kayle', 'photo' => 'photo/Kayle.png','square' => 'square/KayleSquare.png']);
    Champion::create(['name' => 'Kayn', 'photo' => 'photo/Kayn.png','square' => 'square/KaynSquare.png']);
    Champion::create(['name' => 'Kennen', 'photo' => 'photo/Kennen.png','square' => 'square/KennenSquare.png']);
    Champion::create(['name' => 'Kha\'Zix', 'photo' => 'photo/Kha\'Zix.png','square' => 'square/KhaZixSquare.png']);
    Champion::create(['name' => 'Kindred', 'photo' => 'photo/Kindred.png','square' => 'square/KindredSquare.png']);
    Champion::create(['name' => 'Kled', 'photo' => 'photo/Kled.png','square' => 'square/KledSquare.png']);
    Champion::create(['name' => 'Kog\'Maw', 'photo' => 'photo/Kog\'Maw.png','square' => 'square/KogMawSquare.png']);
    Champion::create(['name' => 'LeBlanc', 'photo' => 'photo/LeBlanc.png','square' => 'square/LeBlancSquare.png']);
    Champion::create(['name' => 'Lee Sin', 'photo' => 'photo/Lee Sin.png','square' => 'square/LeeSinSquare.png']);
    Champion::create(['name' => 'Leona', 'photo' => 'photo/Leona.png','square' => 'square/LeonaSquare.png']);
    Champion::create(['name' => 'Lillia', 'photo' => 'photo/Lillia.png','square' => 'square/LilliaSquare.png']);
    Champion::create(['name' => 'Lissandra', 'photo' => 'photo/Lissandra.png','square' => 'square/LissandraSquare.png']);
    Champion::create(['name' => 'Lucian', 'photo' => 'photo/Lucian.png','square' => 'square/LucianSquare.png']);
    Champion::create(['name' => 'Lulu', 'photo' => 'photo/Lulu.png','square' => 'square/LuluSquare.png']);
    Champion::create(['name' => 'Lux', 'photo' => 'photo/Lux.png','square' => 'square/LuxSquare.png']);
    Champion::create(['name' => 'Malphite', 'photo' => 'photo/Malphite.png','square' => 'square/MalphiteSquare.png']);
    Champion::create(['name' => 'Malzahar', 'photo' => 'photo/Malzahar.png','square' => 'square/MalzaharSquare.png']);
    Champion::create(['name' => 'Maokai', 'photo' => 'photo/Maokai.png','square' => 'square/MaokaiSquare.png']);
    Champion::create(['name' => 'Master Yi', 'photo' => 'photo/Master Yi.png','square' => 'square/MasterYiSquare.png']);
    Champion::create(['name' => 'Miss Fortune', 'photo' => 'photo/Miss Fortune.png','square' => 'square/MissFortuneSquare.png']);
    Champion::create(['name' => 'Mordekaiser', 'photo' => 'photo/Mordekaiser.png','square' => 'square/MordekaiserSquare.png']);
    Champion::create(['name' => 'Morgana', 'photo' => 'photo/Morgana.png','square' => 'square/MorganaSquare.png']);
    Champion::create(['name' => 'Nami', 'photo' => 'photo/Nami.png','square' => 'square/NamiSquare.png']);
    Champion::create(['name' => 'Nasus', 'photo' => 'photo/Nasus.png','square' => 'square/NasusSquare.png']);
    Champion::create(['name' => 'Nautilus', 'photo' => 'photo/Nautilus.png','square' => 'square/NautilusSquare.png']);
    Champion::create(['name' => 'Neeko', 'photo' => 'photo/Neeko.png','square' => 'square/NeekoSquare.png']);
    Champion::create(['name' => 'Nidalee', 'photo' => 'photo/Nidalee.png','square' => 'square/NidaleeSquare.png']);
    Champion::create(['name' => 'Nocturne', 'photo' => 'photo/Nocturne.png','square' => 'square/NocturneSquare.png']);
    Champion::create(['name' => 'Nunu & Willump', 'photo' => 'photo/Nunu & Willump.png','square' => 'square/NunuWillumpSquare.png']);
    Champion::create(['name' => 'Olaf', 'photo' => 'photo/Olaf.png','square' => 'square/OlafSquare.png']);
    Champion::create(['name' => 'Orianna', 'photo' => 'photo/Orianna.png','square' => 'square/OriannaSquare.png']);
    Champion::create(['name' => 'Ornn', 'photo' => 'photo/Ornn.png','square' => 'square/OrnnSquare.png']);
    Champion::create(['name' => 'Pantheon', 'photo' => 'photo/Pantheon.png','square' => 'square/PantheonSquare.png']);
    Champion::create(['name' => 'Poppy', 'photo' => 'photo/Poppy.png','square' => 'square/PoppySquare.png']);
    Champion::create(['name' => 'Pyke', 'photo' => 'photo/Pyke.png','square' => 'square/PykeSquare.png']);
    Champion::create(['name' => 'Qiyana', 'photo' => 'photo/Qiyana.png','square' => 'square/QiyanaSquare.png']);
    Champion::create(['name' => 'Quinn', 'photo' => 'photo/Quinn.png','square' => 'square/QuinnSquare.png']);
    Champion::create(['name' => 'Rakan', 'photo' => 'photo/Rakan.png','square' => 'square/RakanSquare.png']);
    Champion::create(['name' => 'Rammus', 'photo' => 'photo/Rammus.png','square' => 'square/RammusSquare.png']);
    Champion::create(['name' => 'Rell', 'photo' => 'photo/Rell.png','square' => 'square/RellSquare.png']);
    Champion::create(['name' => 'Rek\'Sai', 'photo' => 'photo/Rek\'Sai.png','square' => 'square/RekSaiSquare.png']);
    Champion::create(['name' => 'Renekton', 'photo' => 'photo/Renekton.png','square' => 'square/RenektonSquare.png']);
    Champion::create(['name' => 'Rengar', 'photo' => 'photo/Rengar.png','square' => 'square/RengarSquare.png']);
    Champion::create(['name' => 'Riven', 'photo' => 'photo/Riven.png','square' => 'square/RivenSquare.png']);
    Champion::create(['name' => 'Rumble', 'photo' => 'photo/Rumble.png','square' => 'square/RumbleSquare.png']);
    Champion::create(['name' => 'Ryze', 'photo' => 'photo/Ryze.png','square' => 'square/RyzeSquare.png']);
    Champion::create(['name' => 'Samira', 'photo' => 'photo/Samira.png','square' => 'square/SamiraSquare.png']);
    Champion::create(['name' => 'Sejuani', 'photo' => 'photo/Sejuani.png','square' => 'square/SejuaniSquare.png']);
    Champion::create(['name' => 'Seraphine', 'photo' => 'photo/Seraphine.png','square' => 'square/SeraphineSquare.png']);
    Champion::create(['name' => 'Sett', 'photo' => 'photo/Sett.png','square' => 'square/SettSquare.png']);
    Champion::create(['name' => 'Shaco', 'photo' => 'photo/Shaco.png','square' => 'square/ShacoSquare.png']);
    Champion::create(['name' => 'Shen', 'photo' => 'photo/Shen.png','square' => 'square/ShenSquare.png']);
    Champion::create(['name' => 'Shyvana', 'photo' => 'photo/Shyvana.png','square' => 'square/ShyvanaSquare.png']);
    Champion::create(['name' => 'Singed', 'photo' => 'photo/Singed.png','square' => 'square/SingedSquare.png']);
    Champion::create(['name' => 'Sion', 'photo' => 'photo/Sion.png','square' => 'square/SionSquare.png']);
    Champion::create(['name' => 'Sivir', 'photo' => 'photo/Sivir.png','square' => 'square/SivirSquare.png']);
    Champion::create(['name' => 'Skarner', 'photo' => 'photo/Skarner.png','square' => 'square/SkarnerSquare.png']);
    Champion::create(['name' => 'Sona', 'photo' => 'photo/Sona.png','square' => 'square/SonaSquare.png']);
    Champion::create(['name' => 'Soraka', 'photo' => 'photo/Soraka.png','square' => 'square/SorakaSquare.png']);
    Champion::create(['name' => 'Swain', 'photo' => 'photo/Swain.png','square' => 'square/SwainSquare.png']);
    Champion::create(['name' => 'Sylas', 'photo' => 'photo/Sylas.png','square' => 'square/SylasSquare.png']);
    Champion::create(['name' => 'Syndra', 'photo' => 'photo/Syndra.png','square' => 'square/SyndraSquare.png']);
    Champion::create(['name' => 'Tahm Kench', 'photo' => 'photo/Tahm Kench.png','square' => 'square/TahmKenchSquare.png']);
    Champion::create(['name' => 'Taliyah', 'photo' => 'photo/Taliyah.png','square' => 'square/TaliyahSquare.png']);
    Champion::create(['name' => 'Talon', 'photo' => 'photo/Talon.png','square' => 'square/TalonSquare.png']);
    Champion::create(['name' => 'Taric', 'photo' => 'photo/Taric.png','square' => 'square/TaricSquare.png']);
    Champion::create(['name' => 'Teemo', 'photo' => 'photo/Teemo.png','square' => 'square/TeemoSquare.png']);
    Champion::create(['name' => 'Thresh', 'photo' => 'photo/Thresh.png','square' => 'square/ThreshSquare.png']);
    Champion::create(['name' => 'Tristana', 'photo' => 'photo/Tristana.png','square' => 'square/TristanaSquare.png']);
    Champion::create(['name' => 'Trundle', 'photo' => 'photo/Trundle.png','square' => 'square/TrundleSquare.png']);
    Champion::create(['name' => 'Tryndamere', 'photo' => 'photo/Tryndamere.png','square' => 'square/TryndamereSquare.png']);
    Champion::create(['name' => 'Twisted Fate', 'photo' => 'photo/Twisted Fate.png','square' => 'square/TwistedFateSquare.png']);
    Champion::create(['name' => 'Twitch', 'photo' => 'photo/Twitch.png','square' => 'square/TwitchSquare.png']);
    Champion::create(['name' => 'Udyr', 'photo' => 'photo/Udyr.png','square' => 'square/UdyrSquare.png']);
    Champion::create(['name' => 'Urgot', 'photo' => 'photo/Urgot.png','square' => 'square/UrgotSquare.png']);
    Champion::create(['name' => 'Varus', 'photo' => 'photo/Varus.png','square' => 'square/VarusSquare.png']);
    Champion::create(['name' => 'Vayne', 'photo' => 'photo/Vayne.png','square' => 'square/VayneSquare.png']);
    Champion::create(['name' => 'Veigar', 'photo' => 'photo/Veigar.png','square' => 'square/VeigarSquare.png']);
    Champion::create(['name' => 'Vel\'Koz', 'photo' => 'photo/Vel\'Koz.png','square' => 'square/VelKozSquare.png']);
    Champion::create(['name' => 'Vi', 'photo' => 'photo/Vi.png','square' => 'square/ViSquare.png']);
    Champion::create(['name' => 'Viego', 'photo' => 'photo/Viego.png','square' => 'square/ViegoSquare.png']);
    Champion::create(['name' => 'Viktor', 'photo' => 'photo/Viktor.png','square' => 'square/ViktorSquare.png']);
    Champion::create(['name' => 'Vladimir', 'photo' => 'photo/Vladimir.png','square' => 'square/VladimirSquare.png']);
    Champion::create(['name' => 'Volibear', 'photo' => 'photo/Volibear.png','square' => 'square/VolibearSquare.png']);
    Champion::create(['name' => 'Warwick', 'photo' => 'photo/Warwick.png','square' => 'square/WarwickSquare.png']);
    Champion::create(['name' => 'Wukong', 'photo' => 'photo/Wukong.png','square' => 'square/WukongSquare.png']);
    Champion::create(['name' => 'Xayah', 'photo' => 'photo/Xayah.png','square' => 'square/XayahSquare.png']);
    Champion::create(['name' => 'Xerath', 'photo' => 'photo/Xerath.png','square' => 'square/XerathSquare.png']);
    Champion::create(['name' => 'Xin Zhao', 'photo' => 'photo/Xin Zhao.png','square' => 'square/XinZhaoSquare.png']);
    Champion::create(['name' => 'Yasuo', 'photo' => 'photo/Yasuo.png','square' => 'square/YasuoSquare.png']);
    Champion::create(['name' => 'Yone', 'photo' => 'photo/Yone.png','square' => 'square/YoneSquare.png']);
    Champion::create(['name' => 'Yorick', 'photo' => 'photo/Yorick.png','square' => 'square/YorickSquare.png']);
    Champion::create(['name' => 'Yuumi', 'photo' => 'photo/Yuumi.png','square' => 'square/YuumiSquare.png']);
    Champion::create(['name' => 'Zac', 'photo' => 'photo/Zac.png','square' => 'square/ZacSquare.png']);
    Champion::create(['name' => 'Zed', 'photo' => 'photo/Zed.png','square' => 'square/ZedSquare.png']);
    Champion::create(['name' => 'Ziggs', 'photo' => 'photo/Ziggs.png','square' => 'square/ZiggsSquare.png']);
    Champion::create(['name' => 'Zilean', 'photo' => 'photo/Zilean.png','square' => 'square/ZileanSquare.png']);
    Champion::create(['name' => 'Zoe', 'photo' => 'photo/Zoe.png','square' => 'square/ZoeSquare.png']);
    Champion::create(['name' => 'Zyra', 'photo' => 'photo/Zyra.png','square' => 'square/ZyraSquare.png']);
    Champion::create(['name' => 'Seraphine', 'photo' => 'photo/Seraphine.png','square' => 'square/SeraphineSquare.png']);
    Champion::create(['name' => 'Gwen', 'photo' => 'photo/Gwen.png','square' => 'square/GwenSquare.png']);
    Champion::create(['name' => 'Akshan', 'photo' => 'photo/Akshan.png','square' => 'square/AkshanSquare.png']);
    Champion::create(['name' => 'Vex', 'photo' => 'photo/Vex.png','square' => 'square/VexSquare.png']);
    Champion::create(['name' => 'Zeri', 'photo' => 'photo/Zeri.png','square' => 'square/ZeriSquare.png']);
    Champion::create(['name' => 'Renata Glasc', 'photo' => 'photo/Renata Glasc.png','square' => 'square/RenataGlascSquare.png']);
    }
}
