<?php

namespace Database\Seeders;
use App\Models\Champion;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ChampionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void {
    Champion::create(['name' => 'Aatrox', 'photo' => 'photo/Aatrox.png','square' => 'square/Aatroxsquare.webp']);
    Champion::create(['name' => 'Ahri', 'photo' => 'photo/Ahri.png','square' => 'square/Ahrisquare.webp']);
    Champion::create(['name' => 'Akali', 'photo' => 'photo/Akali.png','square' => 'square/Akalisquare.webp']);
    Champion::create(['name' => 'Alistar', 'photo' => 'photo/Alistar.png','square' => 'square/Alistarsquare.webp']);
    Champion::create(['name' => 'Amumu', 'photo' => 'photo/Amumu.png','square' => 'square/Amumusquare.webp']);
    Champion::create(['name' => 'Anivia', 'photo' => 'photo/Aanivia.png','square' => 'square/Aniviasquare.webp']);
    Champion::create(['name' => 'Annie', 'photo' => 'photo/Annie.png','square' => 'square/Anniesquare.webp']);
    Champion::create(['name' => 'Aphelios', 'photo'  => 'photo/Aphelios.png','square' => 'square/Apheliossquare.webp']);
    Champion::create(['name' => 'Ashe', 'photo' => 'photo/Ashe.png','square' => 'square/Ashesquare.webp']);
    Champion::create(['name' => 'Aurelion Sol', 'photo' => 'photo/Aurelion Sol.png','square' => 'square/AurelionSolsquare.webp']);
    Champion::create(['name' => 'Azir', 'photo' => 'photo/Azir.png','square' => 'square/Azirsquare.webp']);
    Champion::create(['name' => 'Bard', 'photo' => 'photo/Bard.png','square' => 'square/Bardsquare.webp']);
    Champion::create(['name' => 'Blitzcrank', 'photo' => 'photo/Blitzcrank.png','square' => 'square/Blitzcranksquare.webp']);
    Champion::create(['name' => 'Brand', 'photo' => 'photo/Brand.png','square' => 'square/Brandsquare.webp']);
    Champion::create(['name' => 'Braum', 'photo' => 'photo/Braum.png','square' => 'square/Braumsquare.webp']);
    Champion::create(['name' => 'Caitlyn', 'photo' => 'photo/Caitlyn.png','square' => 'square/Caitlynsquare.webp']);
    Champion::create(['name' => 'Camille', 'photo' => 'photo/Camille.png','square' => 'square/Camillesquare.webp']);
    Champion::create(['name' => 'Cassiopeia', 'photo' => 'photo/Cassiopeia.png','square' => 'square/Cassiopeiasquare.webp']);
    Champion::create(['name' => 'Cho\'Gath', 'photo' => 'photo/Cho\'Gath.png','square' => 'square/ChoGathsquare.webp']);
    Champion::create(['name' => 'Corki', 'photo' => 'photo/Corki.png','square' => 'square/Corkisquare.webp']);
    Champion::create(['name' => 'Darius', 'photo' => 'photo/Darius.png','square' => 'square/Dariussquare.webp']);
    Champion::create(['name' => 'Diana', 'photo' => 'photo/Diana.png','square' => 'square/Dianasquare.webp']);
    Champion::create(['name' => 'Dr. Mundo', 'photo' => 'photo/Dr. Mundo.png','square' => 'square/DrMundosquare.webp']);
    Champion::create(['name' => 'Draven', 'photo' => 'photo/Draven.png','square' => 'square/Dravensquare.webp']);
    Champion::create(['name' => 'Ekko', 'photo' => 'photo/Ekko.png','square' => 'square/Ekkosquare.webp']);
    Champion::create(['name' => 'Elise', 'photo' => 'photo/Elise.png','square' => 'square/Elisesquare.webp']);
    Champion::create(['name' => 'Evelynn', 'photo' => 'photo/Evelynn.png','square' => 'square/Evelynnsquare.webp']);
    Champion::create(['name' => 'Ezreal', 'photo' => 'photo/Ezreal.png','square' => 'square/Ezrealsquare.webp']);
    Champion::create(['name' => 'Fiddlesticks', 'photo' => 'photo/Fiddlesticks.png','square' => 'square/Fiddlestickssquare.webp']);
    Champion::create(['name' => 'Fiora', 'photo' => 'photo/Fiora.png','square' => 'square/Fiorasquare.webp']);
    Champion::create(['name' => 'Fizz', 'photo' => 'photo/Fizz.png','square' => 'square/Fizzsquare.webp']);
    Champion::create(['name' => 'Galio', 'photo' => 'photo/Galio.png','square' => 'square/Galiosquare.webp']);
    Champion::create(['name' => 'Gangplank', 'photo' => 'photo/Gangplank.png','square' => 'square/Gangplanksquare.webp']);
    Champion::create(['name' => 'Garen', 'photo' => 'photo/Garen.png','square' => 'square/Garensquare.webp']);
    Champion::create(['name' => 'Gnar', 'photo' => 'photo/Gnar.png','square' => 'square/Gnarsquare.webp']);
    Champion::create(['name' => 'Gragas', 'photo' => 'photo/Gragas.png','square' => 'square/Gragassquare.webp']);
    Champion::create(['name' => 'Graves', 'photo' => 'photo/Graves.png','square' => 'square/Gravessquare.webp']);
    Champion::create(['name' => 'Hecarim', 'photo' => 'photo/Hecarim.png','square' => 'square/Hecarimsquare.webp']);
    Champion::create(['name' => 'Heimerdinger', 'photo' => 'photo/Heimerdinger.png','square' => 'square/Heimerdingersquare.webp']);
    Champion::create(['name' => 'Illaoi', 'photo' => 'photo/Illaoi.png','square' => 'square/Illaoisquare.webp']);
    Champion::create(['name' => 'Irelia', 'photo' => 'photo/Irelia.png','square' => 'square/Ireliasquare.webp']);
    Champion::create(['name' => 'Ivern', 'photo' => 'photo/Ivern.png','square' => 'square/Ivernsquare.webp']);
    Champion::create(['name' => 'Janna', 'photo' => 'photo/Janna.png','square' => 'square/Jannasquare.webp']);
    Champion::create(['name' => 'Jarvan IV', 'photo' => 'photo/Jarvan IV.png','square' => 'square/JarvanIVsquare.webp']);
    Champion::create(['name' => 'Jax', 'photo' => 'photo/Jax.png','square' => 'square/Jaxsquare.webp']);
    Champion::create(['name' => 'Jayce', 'photo' => 'photo/Jayce.png','square' => 'square/Jaycesquare.webp']);
    Champion::create(['name' => 'Jhin', 'photo' => 'photo/Jhin.png','square' => 'square/Jhinsquare.webp']);
    Champion::create(['name' => 'Jinx', 'photo' => 'photo/Jinx.png','square' => 'square/Jinxsquare.webp']);
    Champion::create(['name' => 'Kai\'Sa', 'photo' => 'photo/Kai\'Sa.png','square' => 'square/KaiSasquare.webp']);
    Champion::create(['name' => 'Kalista', 'photo' => 'photo/Kalista.png','square' => 'square/Kalistasquare.webp']);
    Champion::create(['name' => 'Karma', 'photo' => 'photo/Karma.png','square' => 'square/Karmasquare.webp']);
    Champion::create(['name' => 'Karthus', 'photo' => 'photo/Karthus.png','square' => 'square/Karthussquare.webp']);
    Champion::create(['name' => 'Kassadin', 'photo' => 'photo/Kassadin.png','square' => 'square/Kassadinsquare.webp']);
    Champion::create(['name' => 'Katarina', 'photo' => 'photo/Katarina.png','square' => 'square/Katarinasquare.webp']);
    Champion::create(['name' => 'Kayle', 'photo' => 'photo/Kayle.png','square' => 'square/Kaylesquare.webp']);
    Champion::create(['name' => 'Kayn', 'photo' => 'photo/Kayn.png','square' => 'square/Kaynsquare.webp']);
    Champion::create(['name' => 'Kennen', 'photo' => 'photo/Kennen.png','square' => 'square/Kennensquare.webp']);
    Champion::create(['name' => 'Kha\'Zix', 'photo' => 'photo/Kha\'Zix.png','square' => 'square/KhaZixsquare.webp']);
    Champion::create(['name' => 'Kindred', 'photo' => 'photo/Kindred.png','square' => 'square/Kindredsquare.webp']);
    Champion::create(['name' => 'Kled', 'photo' => 'photo/Kled.png','square' => 'square/Kledsquare.webp']);
    Champion::create(['name' => 'Kog\'Maw', 'photo' => 'photo/Kog\'Maw.png','square' => 'square/KogMawsquare.webp']);
    Champion::create(['name' => 'LeBlanc', 'photo' => 'photo/LeBlanc.png','square' => 'square/LeBlancsquare.webp']);
    Champion::create(['name' => 'Lee Sin', 'photo' => 'photo/Lee Sin.png','square' => 'square/LeeSinsquare.webp']);
    Champion::create(['name' => 'Leona', 'photo' => 'photo/Leona.png','square' => 'square/Leonasquare.webp']);
    Champion::create(['name' => 'Lillia', 'photo' => 'photo/Lillia.png','square' => 'square/Lilliasquare.webp']);
    Champion::create(['name' => 'Lissandra', 'photo' => 'photo/Lissandra.png','square' => 'square/Lissandrasquare.webp']);
    Champion::create(['name' => 'Lucian', 'photo' => 'photo/Lucian.png','square' => 'square/Luciansquare.webp']);
    Champion::create(['name' => 'Lulu', 'photo' => 'photo/Lulu.png','square' => 'square/Lulusquare.webp']);
    Champion::create(['name' => 'Lux', 'photo' => 'photo/Lux.png','square' => 'square/Luxsquare.webp']);
    Champion::create(['name' => 'Malphite', 'photo' => 'photo/Malphite.png','square' => 'square/Malphitesquare.webp']);
    Champion::create(['name' => 'Malzahar', 'photo' => 'photo/Malzahar.png','square' => 'square/Malzaharsquare.webp']);
    Champion::create(['name' => 'Maokai', 'photo' => 'photo/Maokai.png','square' => 'square/Maokaisquare.webp']);
    Champion::create(['name' => 'Master Yi', 'photo' => 'photo/Master Yi.png','square' => 'square/MasterYisquare.webp']);
    Champion::create(['name' => 'Miss Fortune', 'photo' => 'photo/Miss Fortune.png','square' => 'square/MissFortunesquare.webp']);
    Champion::create(['name' => 'Mordekaiser', 'photo' => 'photo/Mordekaiser.png','square' => 'square/Mordekaisersquare.webp']);
    Champion::create(['name' => 'Morgana', 'photo' => 'photo/Morgana.png','square' => 'square/Morganasquare.webp']);
    Champion::create(['name' => 'Nami', 'photo' => 'photo/Nami.png','square' => 'square/Namisquare.webp']);
    Champion::create(['name' => 'Nasus', 'photo' => 'photo/Nasus.png','square' => 'square/Nasussquare.webp']);
    Champion::create(['name' => 'Nautilus', 'photo' => 'photo/Nautilus.png','square' => 'square/Nautilussquare.webp']);
    Champion::create(['name' => 'Neeko', 'photo' => 'photo/Neeko.png','square' => 'square/Neekosquare.webp']);
    Champion::create(['name' => 'Nidalee', 'photo' => 'photo/Nidalee.png','square' => 'square/Nidaleesquare.webp']);
    Champion::create(['name' => 'Nocturne', 'photo' => 'photo/Nocturne.png','square' => 'square/Nocturnesquare.webp']);
    Champion::create(['name' => 'Nunu & Willump', 'photo' => 'photo/Nunu & Willump.png','square' => 'square/NunuWillumpsquare.webp']);
    Champion::create(['name' => 'Olaf', 'photo' => 'photo/Olaf.png','square' => 'square/Olafsquare.webp']);
    Champion::create(['name' => 'Orianna', 'photo' => 'photo/Orianna.png','square' => 'square/Oriannasquare.webp']);
    Champion::create(['name' => 'Ornn', 'photo' => 'photo/Ornn.png','square' => 'square/Ornnsquare.webp']);
    Champion::create(['name' => 'Pantheon', 'photo' => 'photo/Pantheon.png','square' => 'square/Pantheonsquare.webp']);
    Champion::create(['name' => 'Poppy', 'photo' => 'photo/Poppy.png','square' => 'square/Poppysquare.webp']);
    Champion::create(['name' => 'Pyke', 'photo' => 'photo/Pyke.png','square' => 'square/Pykesquare.webp']);
    Champion::create(['name' => 'Qiyana', 'photo' => 'photo/Qiyana.png','square' => 'square/Qiyanasquare.webp']);
    Champion::create(['name' => 'Quinn', 'photo' => 'photo/Quinn.png','square' => 'square/Quinnsquare.webp']);
    Champion::create(['name' => 'Rakan', 'photo' => 'photo/Rakan.png','square' => 'square/Rakansquare.webp']);
    Champion::create(['name' => 'Rammus', 'photo' => 'photo/Rammus.png','square' => 'square/Rammussquare.webp']);
    Champion::create(['name' => 'Rell', 'photo' => 'photo/Rell.png','square' => 'square/Rellsquare.webp']);
    Champion::create(['name' => 'Rek\'Sai', 'photo' => 'photo/Rek\'Sai.png','square' => 'square/RekSaisquare.webp']);
    Champion::create(['name' => 'Renekton', 'photo' => 'photo/Renekton.png','square' => 'square/Renektonsquare.webp']);
    Champion::create(['name' => 'Rengar', 'photo' => 'photo/Rengar.png','square' => 'square/Rengarsquare.webp']);
    Champion::create(['name' => 'Riven', 'photo' => 'photo/Riven.png','square' => 'square/Rivensquare.webp']);
    Champion::create(['name' => 'Rumble', 'photo' => 'photo/Rumble.png','square' => 'square/Rumblesquare.webp']);
    Champion::create(['name' => 'Ryze', 'photo' => 'photo/Ryze.png','square' => 'square/Ryzesquare.webp']);
    Champion::create(['name' => 'Samira', 'photo' => 'photo/Samira.png','square' => 'square/Samirasquare.webp']);
    Champion::create(['name' => 'Sejuani', 'photo' => 'photo/Sejuani.png','square' => 'square/Sejuanisquare.webp']);
    Champion::create(['name' => 'Seraphine', 'photo' => 'photo/Seraphine.png','square' => 'square/Seraphinesquare.webp']);
    Champion::create(['name' => 'Sett', 'photo' => 'photo/Sett.png','square' => 'square/Settsquare.webp']);
    Champion::create(['name' => 'Shaco', 'photo' => 'photo/Shaco.png','square' => 'square/Shacosquare.webp']);
    Champion::create(['name' => 'Shen', 'photo' => 'photo/Shen.png','square' => 'square/Shensquare.webp']);
    Champion::create(['name' => 'Shyvana', 'photo' => 'photo/Shyvana.png','square' => 'square/Shyvanasquare.webp']);
    Champion::create(['name' => 'Singed', 'photo' => 'photo/Singed.png','square' => 'square/Singedsquare.webp']);
    Champion::create(['name' => 'Sion', 'photo' => 'photo/Sion.png','square' => 'square/Sionsquare.webp']);
    Champion::create(['name' => 'Sivir', 'photo' => 'photo/Sivir.png','square' => 'square/Sivirsquare.webp']);
    Champion::create(['name' => 'Skarner', 'photo' => 'photo/Skarner.png','square' => 'square/Skarnersquare.webp']);
    Champion::create(['name' => 'Sona', 'photo' => 'photo/Sona.png','square' => 'square/Sonasquare.webp']);
    Champion::create(['name' => 'Soraka', 'photo' => 'photo/Soraka.png','square' => 'square/Sorakasquare.webp']);
    Champion::create(['name' => 'Swain', 'photo' => 'photo/Swain.png','square' => 'square/Swainsquare.webp']);
    Champion::create(['name' => 'Sylas', 'photo' => 'photo/Sylas.png','square' => 'square/Sylassquare.webp']);
    Champion::create(['name' => 'Syndra', 'photo' => 'photo/Syndra.png','square' => 'square/Syndrasquare.webp']);
    Champion::create(['name' => 'Tahm Kench', 'photo' => 'photo/Tahm Kench.png','square' => 'square/TahmKenchsquare.webp']);
    Champion::create(['name' => 'Taliyah', 'photo' => 'photo/Taliyah.png','square' => 'square/Taliyahsquare.webp']);
    Champion::create(['name' => 'Talon', 'photo' => 'photo/Talon.png','square' => 'square/Talonsquare.webp']);
    Champion::create(['name' => 'Taric', 'photo' => 'photo/Taric.png','square' => 'square/Taricsquare.webp']);
    Champion::create(['name' => 'Teemo', 'photo' => 'photo/Teemo.png','square' => 'square/Teemosquare.webp']);
    Champion::create(['name' => 'Thresh', 'photo' => 'photo/Thresh.png','square' => 'square/Threshsquare.webp']);
    Champion::create(['name' => 'Tristana', 'photo' => 'photo/Tristana.png','square' => 'square/Tristanasquare.webp']);
    Champion::create(['name' => 'Trundle', 'photo' => 'photo/Trundle.png','square' => 'square/Trundlesquare.webp']);
    Champion::create(['name' => 'Tryndamere', 'photo' => 'photo/Tryndamere.png','square' => 'square/Tryndameresquare.webp']);
    Champion::create(['name' => 'Twisted Fate', 'photo' => 'photo/Twisted Fate.png','square' => 'square/TwistedFatesquare.webp']);
    Champion::create(['name' => 'Twitch', 'photo' => 'photo/Twitch.png','square' => 'square/Twitchsquare.webp']);
    Champion::create(['name' => 'Udyr', 'photo' => 'photo/Udyr.png','square' => 'square/Udyrsquare.webp']);
    Champion::create(['name' => 'Urgot', 'photo' => 'photo/Urgot.png','square' => 'square/Urgotsquare.webp']);
    Champion::create(['name' => 'Varus', 'photo' => 'photo/Varus.png','square' => 'square/Varussquare.webp']);
    Champion::create(['name' => 'Vayne', 'photo' => 'photo/Vayne.png','square' => 'square/Vaynesquare.webp']);
    Champion::create(['name' => 'Veigar', 'photo' => 'photo/Veigar.png','square' => 'square/Veigarsquare.webp']);
    Champion::create(['name' => 'Vel\'Koz', 'photo' => 'photo/Vel\'Koz.png','square' => 'square/VelKozsquare.webp']);
    Champion::create(['name' => 'Vi', 'photo' => 'photo/Vi.png','square' => 'square/Visquare.webp']);
    Champion::create(['name' => 'Viego', 'photo' => 'photo/Viego.png','square' => 'square/Viegosquare.webp']);
    Champion::create(['name' => 'Viktor', 'photo' => 'photo/Viktor.png','square' => 'square/Viktorsquare.webp']);
    Champion::create(['name' => 'Vladimir', 'photo' => 'photo/Vladimir.png','square' => 'square/Vladimirsquare.webp']);
    Champion::create(['name' => 'Volibear', 'photo' => 'photo/Volibear.png','square' => 'square/Volibearsquare.webp']);
    Champion::create(['name' => 'Warwick', 'photo' => 'photo/Warwick.png','square' => 'square/Warwicksquare.webp']);
    Champion::create(['name' => 'Wukong', 'photo' => 'photo/Wukong.png','square' => 'square/Wukongsquare.webp']);
    Champion::create(['name' => 'Xayah', 'photo' => 'photo/Xayah.png','square' => 'square/Xayahsquare.webp']);
    Champion::create(['name' => 'Xerath', 'photo' => 'photo/Xerath.png','square' => 'square/Xerathsquare.webp']);
    Champion::create(['name' => 'Xin Zhao', 'photo' => 'photo/Xin Zhao.png','square' => 'square/XinZhaosquare.webp']);
    Champion::create(['name' => 'Yasuo', 'photo' => 'photo/Yasuo.png','square' => 'square/Yasuosquare.webp']);
    Champion::create(['name' => 'Yone', 'photo' => 'photo/Yone.png','square' => 'square/Yonesquare.webp']);
    Champion::create(['name' => 'Yorick', 'photo' => 'photo/Yorick.png','square' => 'square/Yoricksquare.webp']);
    Champion::create(['name' => 'Yuumi', 'photo' => 'photo/Yuumi.png','square' => 'square/Yuumisquare.webp']);
    Champion::create(['name' => 'Zac', 'photo' => 'photo/Zac.png','square' => 'square/Zacsquare.webp']);
    Champion::create(['name' => 'Zed', 'photo' => 'photo/Zed.png','square' => 'square/Zedsquare.webp']);
    Champion::create(['name' => 'Ziggs', 'photo' => 'photo/Ziggs.png','square' => 'square/Ziggssquare.webp']);
    Champion::create(['name' => 'Zilean', 'photo' => 'photo/Zilean.png','square' => 'square/Zileansquare.webp']);
    Champion::create(['name' => 'Zoe', 'photo' => 'photo/Zoe.png','square' => 'square/Zoesquare.webp']);
    Champion::create(['name' => 'Zyra', 'photo' => 'photo/Zyra.png','square' => 'square/Zyrasquare.webp']);
    Champion::create(['name' => 'Seraphine', 'photo' => 'photo/Seraphine.png','square' => 'square/Seraphinesquare.webp']);
    Champion::create(['name' => 'Gwen', 'photo' => 'photo/Gwen.png','square' => 'square/Gwensquare.webp']);
    Champion::create(['name' => 'Akshan', 'photo' => 'photo/Akshan.png','square' => 'square/Akshansquare.webp']);
    Champion::create(['name' => 'Vex', 'photo' => 'photo/Vex.png','square' => 'square/Vexsquare.webp']);
    Champion::create(['name' => 'Zeri', 'photo' => 'photo/Zeri.png','square' => 'square/Zerisquare.webp']);
    Champion::create(['name' => 'Senna', 'photo' => 'photo/Senna.png','square' => 'square/Sennasquare.webp']);
    Champion::create(['name' => 'Bel\'Veth', 'photo' => 'photo/Bel\'Veth.png','square' => 'square/Bel\'Vethsquare.webp']);
    Champion::create(['name' => 'Nilah', 'photo' => 'photo/Nilah.png','square' => 'square/Nilahsquare.webp']);
    Champion::create(['name' => 'K\'Sante', 'photo' => 'photo/K\'Sante.png','square' => 'square/K\'Santesquare.webp']);
    Champion::create(['name' => 'Milio', 'photo' => 'photo/Milio.png','square' => 'square/Miliosquare.webp']);
    Champion::create(['name' => 'Naafiri', 'photo' => 'photo/Naafiri.png','square' => 'square/Naafirisquare.webp']);
    Champion::create(['name' => 'Briar', 'photo' => 'photo/Briar.png','square' => 'square/Briarsquare.webp']);
    Champion::create(['name' => 'Hwei', 'photo' => 'photo/Hwei.png','square' => 'square/Hweisquare.webp']);
    Champion::create(['name' => 'Renata Glasc', 'photo' => 'photo/Renata Glasc.png','square' => 'square/RenataGlascsquare.webp']);
    }
}
