<?php

namespace Database\Seeders;
use App\Models\Champion;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ChampionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void {
    Champion::create(['name' => 'Aatrox', 'photo' => 'photo/Aatrox_0.jpg','square' => 'square/AatroxSquare.png']);
    Champion::create(['name' => 'Ahri', 'photo' => 'photo/Ahri_0.jpg','square' => 'square/AhriSquare.png']);
    Champion::create(['name' => 'Akali', 'photo' => 'photo/Akali_0.jpg','square' => 'square/AkaliSquare.png']);
    Champion::create(['name' => 'Alistar', 'photo' => 'photo/Alistar_0.jpg','square' => 'square/AlistarSquare.png']);
    Champion::create(['name' => 'Amumu', 'photo' => 'photo/Amumu_0.jpg','square' => 'square/AmumuSquare.png']);
    Champion::create(['name' => 'Anivia', 'photo' => 'photo/Aanivia_0.jpg','square' => 'square/AniviaSquare.png']);
    Champion::create(['name' => 'Annie', 'photo' => 'photo/Annie_0.jpg','square' => 'square/AnnieSquare.png']);
    Champion::create(['name' => 'Aphelios', 'photo'  => 'photo/Aphelios_0.jpg','square' => 'square/ApheliosSquare.png']);
    Champion::create(['name' => 'Ashe', 'photo' => 'photo/Ashe_0.jpg','square' => 'square/AsheSquare.png']);
    Champion::create(['name' => 'Aurelion Sol', 'photo' => 'photo/Aurelion Sol_0.jpg','square' => 'square/AurelionSolSquare.png']);
    Champion::create(['name' => 'Azir', 'photo' => 'photo/Azir_0.jpg','square' => 'square/AzirSquare.png']);
    Champion::create(['name' => 'Bard', 'photo' => 'photo/Bard_0.jpg','square' => 'square/BardSquare.png']);
    Champion::create(['name' => 'Blitzcrank', 'photo' => 'photo/Blitzcrank_0.jpg','square' => 'square/BlitzcrankSquare.png']);
    Champion::create(['name' => 'Brand', 'photo' => 'photo/Brand_0.jpg','square' => 'square/BrandSquare.png']);
    Champion::create(['name' => 'Braum', 'photo' => 'photo/Braum_0.jpg','square' => 'square/BraumSquare.png']);
    Champion::create(['name' => 'Caitlyn', 'photo' => 'photo/Caitlyn_0.jpg','square' => 'square/CaitlynSquare.png']);
    Champion::create(['name' => 'Camille', 'photo' => 'photo/Camille_0.jpg','square' => 'square/CamilleSquare.png']);
    Champion::create(['name' => 'Cassiopeia', 'photo' => 'photo/Cassiopeia_0.jpg','square' => 'square/CassiopeiaSquare.png']);
    Champion::create(['name' => 'Cho\'Gath', 'photo' => 'photo/ChoGath_0.jpg','square' => 'square/ChoGathSquare.png']);
    Champion::create(['name' => 'Corki', 'photo' => 'photo/Corki_0.jpg','square' => 'square/CorkiSquare.png']);
    Champion::create(['name' => 'Darius', 'photo' => 'photo/Darius_0.jpg','square' => 'square/DariusSquare.png']);
    Champion::create(['name' => 'Diana', 'photo' => 'photo/Diana_0.jpg','square' => 'square/DianaSquare.png']);
    Champion::create(['name' => 'Dr. Mundo', 'photo' => 'photo/Dr. Mundo_0.jpg','square' => 'square/DrMundoSquare.png']);
    Champion::create(['name' => 'Draven', 'photo' => 'photo/Draven_0.jpg','square' => 'square/DravenSquare.png']);
    Champion::create(['name' => 'Ekko', 'photo' => 'photo/Ekko_0.jpg','square' => 'square/EkkoSquare.png']);
    Champion::create(['name' => 'Elise', 'photo' => 'photo/Elise_0.jpg','square' => 'square/EliseSquare.png']);
    Champion::create(['name' => 'Evelynn', 'photo' => 'photo/Evelynn_0.jpg','square' => 'square/EvelynnSquare.png']);
    Champion::create(['name' => 'Ezreal', 'photo' => 'photo/Ezreal_0.jpg','square' => 'square/EzrealSquare.png']);
    Champion::create(['name' => 'Fiddlesticks', 'photo' => 'photo/Fiddlesticks_0.jpg','square' => 'square/FiddlesticksSquare.png']);
    Champion::create(['name' => 'Fiora', 'photo' => 'photo/Fiora_0.jpg','square' => 'square/FioraSquare.png']);
    Champion::create(['name' => 'Fizz', 'photo' => 'photo/Fizz_0.jpg','square' => 'square/FizzSquare.png']);
    Champion::create(['name' => 'Galio', 'photo' => 'photo/Galio_0.jpg','square' => 'square/GalioSquare.png']);
    Champion::create(['name' => 'Gangplank', 'photo' => 'photo/Gangplank_0.jpg','square' => 'square/GangplankSquare.png']);
    Champion::create(['name' => 'Garen', 'photo' => 'photo/Garen_0.jpg','square' => 'square/GarenSquare.png']);
    Champion::create(['name' => 'Gnar', 'photo' => 'photo/Gnar_0.jpg','square' => 'square/GnarSquare.png']);
    Champion::create(['name' => 'Gragas', 'photo' => 'photo/Gragas_0.jpg','square' => 'square/GragasSquare.png']);
    Champion::create(['name' => 'Graves', 'photo' => 'photo/Graves_0.jpg','square' => 'square/GravesSquare.png']);
    Champion::create(['name' => 'Hecarim', 'photo' => 'photo/Hecarim_0.jpg','square' => 'square/HecarimSquare.png']);
    Champion::create(['name' => 'Heimerdinger', 'photo' => 'photo/Heimerdinger_0.jpg','square' => 'square/HeimerdingerSquare.png']);
    Champion::create(['name' => 'Illaoi', 'photo' => 'photo/Illaoi_0.jpg','square' => 'square/IllaoiSquare.png']);
    Champion::create(['name' => 'Irelia', 'photo' => 'photo/Irelia_0.jpg','square' => 'square/IreliaSquare.png']);
    Champion::create(['name' => 'Ivern', 'photo' => 'photo/Ivern_0.jpg','square' => 'square/IvernSquare.png']);
    Champion::create(['name' => 'Janna', 'photo' => 'photo/Janna_0.jpg','square' => 'square/JannaSquare.png']);
    Champion::create(['name' => 'Jarvan IV', 'photo' => 'photo/JarvanIV_0.jpg','square' => 'square/JarvanIVSquare.png']);
    Champion::create(['name' => 'Jax', 'photo' => 'photo/Jax_0.jpg','square' => 'square/JaxSquare.png']);
    Champion::create(['name' => 'Jayce', 'photo' => 'photo/Jayce_0.jpg','square' => 'square/JayceSquare.png']);
    Champion::create(['name' => 'Jhin', 'photo' => 'photo/Jhin_0.jpg','square' => 'square/JhinSquare.png']);
    Champion::create(['name' => 'Jinx', 'photo' => 'photo/Jinx_0.jpg','square' => 'square/JinxSquare.png']);
    Champion::create(['name' => 'Kai\'Sa', 'photo' => 'photo/Kaisa_0.jpg','square' => 'square/KaiSaSquare.png']);
    Champion::create(['name' => 'Kalista', 'photo' => 'photo/Kalista_0.jpg','square' => 'square/KalistaSquare.png']);
    Champion::create(['name' => 'Karma', 'photo' => 'photo/Karma_0.jpg','square' => 'square/KarmaSquare.png']);
    Champion::create(['name' => 'Karthus', 'photo' => 'photo/Karthus_0.jpg','square' => 'square/KarthusSquare.png']);
    Champion::create(['name' => 'Kassadin', 'photo' => 'photo/Kassadin_0.jpg','square' => 'square/KassadinSquare.png']);
    Champion::create(['name' => 'Katarina', 'photo' => 'photo/Katarina_0.jpg','square' => 'square/KatarinaSquare.png']);
    Champion::create(['name' => 'Kayle', 'photo' => 'photo/Kayle_0.jpg','square' => 'square/KayleSquare.png']);
    Champion::create(['name' => 'Kayn', 'photo' => 'photo/Kayn_0.jpg','square' => 'square/KaynSquare.png']);
    Champion::create(['name' => 'Kennen', 'photo' => 'photo/Kennen_0.jpg','square' => 'square/KennenSquare.png']);
    Champion::create(['name' => 'Kha\'Zix', 'photo' => 'photo/KhaZix_0.jpg','square' => 'square/KhaZixSquare.png']);
    Champion::create(['name' => 'Kindred', 'photo' => 'photo/Kindred_0.jpg','square' => 'square/KindredSquare.png']);
    Champion::create(['name' => 'Kled', 'photo' => 'photo/Kled_0.jpg','square' => 'square/KledSquare.png']);
    Champion::create(['name' => 'Kog\'Maw', 'photo' => 'photo/KogMaw_0.jpg','square' => 'square/KogMawSquare.png']);
    Champion::create(['name' => 'LeBlanc', 'photo' => 'photo/LeBlanc_0.jpg','square' => 'square/LeBlancSquare.png']);
    Champion::create(['name' => 'Lee Sin', 'photo' => 'photo/LeeSin_0.jpg','square' => 'square/LeeSinSquare.png']);
    Champion::create(['name' => 'Leona', 'photo' => 'photo/Leona_0.jpg','square' => 'square/LeonaSquare.png']);
    Champion::create(['name' => 'Lillia', 'photo' => 'photo/Lillia_0.jpg','square' => 'square/LilliaSquare.png']);
    Champion::create(['name' => 'Lissandra', 'photo' => 'photo/Lissandra_0.jpg','square' => 'square/LissandraSquare.png']);
    Champion::create(['name' => 'Lucian', 'photo' => 'photo/Lucian_0.jpg','square' => 'square/LucianSquare.png']);
    Champion::create(['name' => 'Lulu', 'photo' => 'photo/Lulu_0.jpg','square' => 'square/LuluSquare.png']);
    Champion::create(['name' => 'Lux', 'photo' => 'photo/Lux_0.jpg','square' => 'square/LuxSquare.png']);
    Champion::create(['name' => 'Malphite', 'photo' => 'photo/Malphite_0.jpg','square' => 'square/MalphiteSquare.png']);
    Champion::create(['name' => 'Malzahar', 'photo' => 'photo/Malzahar_0.jpg','square' => 'square/MalzaharSquare.png']);
    Champion::create(['name' => 'Maokai', 'photo' => 'photo/Maokai_0.jpg','square' => 'square/MaokaiSquare.png']);
    Champion::create(['name' => 'Master Yi', 'photo' => 'photo/MasterYi_0.jpg','square' => 'square/MasterYiSquare.png']);
    Champion::create(['name' => 'Miss Fortune', 'photo' => 'photo/Miss Fortune_0.jpg','square' => 'square/MissFortuneSquare.png']);
    Champion::create(['name' => 'Mordekaiser', 'photo' => 'photo/Mordekaiser_0.jpg','square' => 'square/MordekaiserSquare.png']);
    Champion::create(['name' => 'Morgana', 'photo' => 'photo/Morgana_0.jpg','square' => 'square/MorganaSquare.png']);
    Champion::create(['name' => 'Nami', 'photo' => 'photo/Nami_0.jpg','square' => 'square/NamiSquare.png']);
    Champion::create(['name' => 'Nasus', 'photo' => 'photo/Nasus_0.jpg','square' => 'square/NasusSquare.png']);
    Champion::create(['name' => 'Nautilus', 'photo' => 'photo/Nautilus_0.jpg','square' => 'square/NautilusSquare.png']);
    Champion::create(['name' => 'Neeko', 'photo' => 'photo/Neeko_0.jpg','square' => 'square/NeekoSquare.png']);
    Champion::create(['name' => 'Nidalee', 'photo' => 'photo/Nidalee_0.jpg','square' => 'square/NidaleeSquare.png']);
    Champion::create(['name' => 'Nocturne', 'photo' => 'photo/Nocturne_0.jpg','square' => 'square/NocturneSquare.png']);
    Champion::create(['name' => 'Nunu & Willump', 'photo' => 'photo/Nunu&Willump_0.jpg','square' => 'square/NunuWillumpSquare.png']);
    Champion::create(['name' => 'Olaf', 'photo' => 'photo/Olaf_0.jpg','square' => 'square/OlafSquare.png']);
    Champion::create(['name' => 'Orianna', 'photo' => 'photo/Orianna_0.jpg','square' => 'square/OriannaSquare.png']);
    Champion::create(['name' => 'Ornn', 'photo' => 'photo/Ornn_0.jpg','square' => 'square/OrnnSquare.png']);
    Champion::create(['name' => 'Pantheon', 'photo' => 'photo/Pantheon_0.jpg','square' => 'square/PantheonSquare.png']);
    Champion::create(['name' => 'Poppy', 'photo' => 'photo/Poppy_0.jpg','square' => 'square/PoppySquare.png']);
    Champion::create(['name' => 'Pyke', 'photo' => 'photo/Pyke_0.jpg','square' => 'square/PykeSquare.png']);
    Champion::create(['name' => 'Qiyana', 'photo' => 'photo/Qiyana_0.jpg','square' => 'square/QiyanaSquare.png']);
    Champion::create(['name' => 'Quinn', 'photo' => 'photo/Quinn_0.jpg','square' => 'square/QuinnSquare.png']);
    Champion::create(['name' => 'Rakan', 'photo' => 'photo/Rakan_0.jpg','square' => 'square/RakanSquare.png']);
    Champion::create(['name' => 'Rammus', 'photo' => 'photo/Rammus_0.jpg','square' => 'square/RammusSquare.png']);
    Champion::create(['name' => 'Rell', 'photo' => 'photo/Rell_0.jpg','square' => 'square/RellSquare.png']);
    Champion::create(['name' => 'Rek\'Sai', 'photo' => 'photo/RekSai_0.jpg','square' => 'square/RekSaiSquare.png']);
    Champion::create(['name' => 'Renekton', 'photo' => 'photo/Renekton_0.jpg','square' => 'square/RenektonSquare.png']);
    Champion::create(['name' => 'Rengar', 'photo' => 'photo/Rengar_0.jpg','square' => 'square/RengarSquare.png']);
    Champion::create(['name' => 'Riven', 'photo' => 'photo/Riven_0.jpg','square' => 'square/RivenSquare.png']);
    Champion::create(['name' => 'Rumble', 'photo' => 'photo/Rumble_0.jpg','square' => 'square/RumbleSquare.png']);
    Champion::create(['name' => 'Ryze', 'photo' => 'photo/Ryze_0.jpg','square' => 'square/RyzeSquare.png']);
    Champion::create(['name' => 'Samira', 'photo' => 'photo/Samira_0.jpg','square' => 'square/SamiraSquare.png']);
    Champion::create(['name' => 'Sejuani', 'photo' => 'photo/Sejuani_0.jpg','square' => 'square/SejuaniSquare.png']);
    Champion::create(['name' => 'Seraphine', 'photo' => 'photo/Seraphine_0.jpg','square' => 'square/SeraphineSquare.png']);
    Champion::create(['name' => 'Sett', 'photo' => 'photo/Sett_0.jpg','square' => 'square/SettSquare.png']);
    Champion::create(['name' => 'Shaco', 'photo' => 'photo/Shaco_0.jpg','square' => 'square/ShacoSquare.png']);
    Champion::create(['name' => 'Shen', 'photo' => 'photo/Shen_0.jpg','square' => 'square/ShenSquare.png']);
    Champion::create(['name' => 'Shyvana', 'photo' => 'photo/Shyvana_0.jpg','square' => 'square/ShyvanaSquare.png']);
    Champion::create(['name' => 'Singed', 'photo' => 'photo/Singed_0.jpg','square' => 'square/SingedSquare.png']);
    Champion::create(['name' => 'Sion', 'photo' => 'photo/Sion_0.jpg','square' => 'square/SionSquare.png']);
    Champion::create(['name' => 'Sivir', 'photo' => 'photo/Sivir_0.jpg','square' => 'square/SivirSquare.png']);
    Champion::create(['name' => 'Skarner', 'photo' => 'photo/Skarner_0.jpg','square' => 'square/SkarnerSquare.png']);
    Champion::create(['name' => 'Sona', 'photo' => 'photo/Sona_0.jpg','square' => 'square/SonaSquare.png']);
    Champion::create(['name' => 'Soraka', 'photo' => 'photo/Soraka_0.jpg','square' => 'square/SorakaSquare.png']);
    Champion::create(['name' => 'Swain', 'photo' => 'photo/Swain_0.jpg','square' => 'square/SwainSquare.png']);
    Champion::create(['name' => 'Sylas', 'photo' => 'photo/Sylas_0.jpg','square' => 'square/SylasSquare.png']);
    Champion::create(['name' => 'Syndra', 'photo' => 'photo/Syndra_0.jpg','square' => 'square/SyndraSquare.png']);
    Champion::create(['name' => 'Tahm Kench', 'photo' => 'photo/TahmKench_0.jpg','square' => 'square/TahmKenchSquare.png']);
    Champion::create(['name' => 'Taliyah', 'photo' => 'photo/Taliyah_0.jpg','square' => 'square/TaliyahSquare.png']);
    Champion::create(['name' => 'Talon', 'photo' => 'photo/Talon_0.jpg','square' => 'square/TalonSquare.png']);
    Champion::create(['name' => 'Taric', 'photo' => 'photo/Taric_0.jpg','square' => 'square/TaricSquare.png']);
    Champion::create(['name' => 'Teemo', 'photo' => 'photo/Teemo_0.jpg','square' => 'square/TeemoSquare.png']);
    Champion::create(['name' => 'Thresh', 'photo' => 'photo/Thresh_0.jpg','square' => 'square/ThreshSquare.png']);
    Champion::create(['name' => 'Tristana', 'photo' => 'photo/Tristana_0.jpg','square' => 'square/TristanaSquare.png']);
    Champion::create(['name' => 'Trundle', 'photo' => 'photo/Trundle_0.jpg','square' => 'square/TrundleSquare.png']);
    Champion::create(['name' => 'Tryndamere', 'photo' => 'photo/Tryndamere_0.jpg','square' => 'square/TryndamereSquare.png']);
    Champion::create(['name' => 'Twisted Fate', 'photo' => 'photo/Twisted Fate_0.jpg','square' => 'square/TwistedFateSquare.png']);
    Champion::create(['name' => 'Twitch', 'photo' => 'photo/Twitch_0.jpg','square' => 'square/TwitchSquare.png']);
    Champion::create(['name' => 'Udyr', 'photo' => 'photo/Udyr_0.jpg','square' => 'square/UdyrSquare.png']);
    Champion::create(['name' => 'Urgot', 'photo' => 'photo/Urgot_0.jpg','square' => 'square/UrgotSquare.png']);
    Champion::create(['name' => 'Varus', 'photo' => 'photo/Varus_0.jpg','square' => 'square/VarusSquare.png']);
    Champion::create(['name' => 'Vayne', 'photo' => 'photo/Vayne_0.jpg','square' => 'square/VayneSquare.png']);
    Champion::create(['name' => 'Veigar', 'photo' => 'photo/Veigar_0.jpg','square' => 'square/VeigarSquare.png']);
    Champion::create(['name' => 'Vel\'Koz', 'photo' => 'photo/VelKoz_0.jpg','square' => 'square/VelKozSquare.png']);
    Champion::create(['name' => 'Vi', 'photo' => 'photo/Vi_0.jpg','square' => 'square/ViSquare.png']);
    Champion::create(['name' => 'Viego', 'photo' => 'photo/Viego_0.jpg','square' => 'square/ViegoSquare.png']);
    Champion::create(['name' => 'Viktor', 'photo' => 'photo/Viktor_0.jpg','square' => 'square/ViktorSquare.png']);
    Champion::create(['name' => 'Vladimir', 'photo' => 'photo/Vladimir_0.jpg','square' => 'square/VladimirSquare.png']);
    Champion::create(['name' => 'Volibear', 'photo' => 'photo/Volibear_0.jpg','square' => 'square/VolibearSquare.png']);
    Champion::create(['name' => 'Warwick', 'photo' => 'photo/Warwick_0.jpg','square' => 'square/WarwickSquare.png']);
    Champion::create(['name' => 'Wukong', 'photo' => 'photo/Wukong_0.jpg','square' => 'square/WukongSquare.png']);
    Champion::create(['name' => 'Xayah', 'photo' => 'photo/Xayah_0.jpg','square' => 'square/XayahSquare.png']);
    Champion::create(['name' => 'Xerath', 'photo' => 'photo/Xerath_0.jpg','square' => 'square/XerathSquare.png']);
    Champion::create(['name' => 'Xin Zhao', 'photo' => 'photo/Xin Zhao_0.jpg','square' => 'square/XinZhaoSquare.png']);
    Champion::create(['name' => 'Yasuo', 'photo' => 'photo/Yasuo_0.jpg','square' => 'square/YasuoSquare.png']);
    Champion::create(['name' => 'Yone', 'photo' => 'photo/Yone_0.jpg','square' => 'square/YoneSquare.png']);
    Champion::create(['name' => 'Yorick', 'photo' => 'photo/Yorick_0.jpg','square' => 'square/YorickSquare.png']);
    Champion::create(['name' => 'Yuumi', 'photo' => 'photo/Yuumi_0.jpg','square' => 'square/YuumiSquare.png']);
    Champion::create(['name' => 'Zac', 'photo' => 'photo/Zac_0.jpg','square' => 'square/ZacSquare.png']);
    Champion::create(['name' => 'Zed', 'photo' => 'photo/Zed_0.jpg','square' => 'square/ZedSquare.png']);
    Champion::create(['name' => 'Ziggs', 'photo' => 'photo/Ziggs_0.jpg','square' => 'square/ZiggsSquare.png']);
    Champion::create(['name' => 'Zilean', 'photo' => 'photo/Zilean_0.jpg','square' => 'square/ZileanSquare.png']);
    Champion::create(['name' => 'Zoe', 'photo' => 'photo/Zoe_0.jpg','square' => 'square/ZoeSquare.png']);
    Champion::create(['name' => 'Zyra', 'photo' => 'photo/Zyra_0.jpg','square' => 'square/ZyraSquare.png']);
    Champion::create(['name' => 'Seraphine', 'photo' => 'photo/Seraphine_0.jpg','square' => 'square/SeraphineSquare.png']);
    Champion::create(['name' => 'Gwen', 'photo' => 'photo/Gwen_0.jpg','square' => 'square/GwenSquare.png']);
    Champion::create(['name' => 'Akshan', 'photo' => 'photo/Akshan_0.jpg','square' => 'square/AkshanSquare.png']);
    Champion::create(['name' => 'Vex', 'photo' => 'photo/Vex_0.jpg','square' => 'square/VexSquare.png']);
    Champion::create(['name' => 'Zeri', 'photo' => 'photo/Zeri_0.jpg','square' => 'square/ZeriSquare.png']);
    Champion::create(['name' => 'Senna', 'photo' => 'photo/Senna_0.jpg','square' => 'square/SennaSquare.png']);
    Champion::create(['name' => 'Bel\'Veth', 'photo' => 'photo/BelVeth_0.jpg','square' => 'square/Bel\'VethSquare.png']);
    Champion::create(['name' => 'Nilah', 'photo' => 'photo/Nilah_0.jpg','square' => 'square/NilahSquare.png']);
    Champion::create(['name' => 'K\'Sante', 'photo' => 'photo/KSante_0.jpg','square' => 'square/K\'SanteSquare.png']);
    Champion::create(['name' => 'Milio', 'photo' => 'photo/Milio_0.jpg','square' => 'square/MilioSquare.png']);
    Champion::create(['name' => 'Naafiri', 'photo' => 'photo/Naafiri_0.jpg','square' => 'square/NaafiriSquare.png']);
    Champion::create(['name' => 'Briar', 'photo' => 'photo/Briar_0.jpg','square' => 'square/BriarSquare.png']);
    Champion::create(['name' => 'Hwei', 'photo' => 'photo/Hwei_0.jpg','square' => 'square/HweiSquare.png']);
    Champion::create(['name' => 'Renata Glasc', 'photo' => 'photo/Renata_0.jpg','square' => 'square/RenataGlascSquare.png']);
    }
}
